### ISSUE TITLE
[Feature Request] Highlight escape sequences and characters like %d and %s

### ISSUE THREAD

**Issue by kkanungo17** [bsides/snazzy-operator-plus#1]
This is especially useful for C code.

**Comment by bsides** [comment]
Hello! 😸 

I don't know if that's possible with vscode right now. I can't seem to find a way to do a granular search for stuff like this. I'll leave this open until I find something about it though.

Thanks for opening this!

**Comment by bsides** [comment]
PS - I forgot I had to publish this - I just published https://github.com/bsides/snazzy-operator-plus/commit/52bcb257c6d35bee50c98e5c7cb9fce19ef71d2a
